export const SOCKET_IO_EVENTS = {
  USER_EMITTED: {
    REGISTER: 'REGISTER',
    MAKE_TRADE: 'MAKE_TRADE',
  },
  SERVER_EMITTED: {
    NEW_USER_REGISTERED: 'NEW_USER_REGISTERED',
    SESSION_KEYS: 'SESSION_KEYS',
  },
} as const;
